### ISSUE TITLE
Constructing an ArpClient can panic

### ISSUE THREAD

**Issue by dblsaiko** [OliLay/arp-toolkit-rust#2]
The call to `interface.create_tx_rx_channels()` in ArpClient::new_with_iface can return Err in case the user the process runs as doesn't have sufficient permissions. The error should be passed through to the caller instead of unconditionally unwrapped to allow handling the error gracefully.

**Comment by OliLay** [comment]
Hi, thanks for reporting this issue. I addressed it in f2c8098. The client now returns a `Result` on all constructors, propagating the error to the caller of the API.
