### ISSUE TITLE
error: failed to select a version for the requirement `pnet = "^0.31"`

### ISSUE THREAD

**Issue by zhang-ray** [OliLay/arp-toolkit-rust#5]
Hello, I met an issue about pnet :

```
arp-toolkit-rust ±|master|→ cargo build
error: failed to select a version for the requirement `pnet = "^0.31"`
candidate versions found which didn't match: 0.29.0, 0.28.0, 0.27.2, ...
location searched: crates.io index
required by package `arp-toolkit v0.3.0 (/works/arp-toolkit-rust/src)`

arp-toolkit-rust ±|master|→ cargo --version &&  rustc --version
cargo 1.58.0 (f01b232bc 2022-01-19)  
rustc 1.58.1 (db9d1b20b 2022-01-20)


```

**Comment by OliLay** [comment]
Hi, 
as [pnet 0.31](https://crates.io/crates/pnet/versions) is available, there must be some issue on your side.
Have you tried e.g. [this](https://users.rust-lang.org/t/solved-cargo-failed-to-select-a-version-not-due-to-conflicts/75817/7)?

**Comment by zhang-ray** [comment]
> 

Hello Oli,

I'd try to build it in a clean Ubuntu 20.04 with cargo 1.65.0 , no error occurred. Maybe this is a cargo's compatibly issue.

**Comment by zhang-ray** [comment]
BTW, maybe these  command can resolve this issue on old-environment :
```
rustup update
cargo update
```
