### ISSUE TITLE
PermissionDenied

### ISSUE THREAD

**Issue by omarandlorraine** [OliLay/arp-toolkit-rust#7]
I am finding I'm unable to instantiate an ARP client using this library.

```rust
pub fn ip(&self) -> std::net::Ipv4Addr{
    let mut client = libarp::client::ArpClient::new().unwrap();
    client.mac_to_ip(self.mac_addr, None).unwrap()
}
```

This gives me the error unless I run my program as Root, which I hope I don't have to do

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', barix/lib.rs:48:59
```

The line number here matches the `libarp::client::ArpClient::new().unwrap()`.

Do you know anything about which permissions I need to grant my user? I have not seen anything in the documentation about this.

**Comment by OliLay** [comment]
Hi, please refer to the bottom of the `README`:
```
Important note: As this library uses Raw sockets, either [set](https://squidarth.com/networking/systems/rc/2018/05/28/using-raw-sockets.html) the CAP_NET_RAW capability or run your program with sudo. (not recommended)
```
So you can set the `CAP_NET_RAW` capability of your program, then you do not need root. This is required because else one is not allowed to use raw sockets.
